import type {
  SourceRef, Bundle, Expert, Journey, FactoryJob, CompanionEvent,
} from "./types";

// ─────────────────────────────── Sources ───────────────────────────────
export const sources: SourceRef[] = [
  { id: "gwi-2025", title: "2025 Global Wellness Economy Monitor", publisher: "Global Wellness Institute", year: "2025", url: "https://globalwellnessinstitute.org/industry-research/2025-global-wellness-economy-monitor/", sourceType: "market" },
  { id: "euromonitor-2026", title: "Beauty and healthspan reshape the $338B consumer health market", publisher: "Euromonitor", year: "2026", url: "https://www.euromonitor.com/", sourceType: "market" },
  { id: "gvr-supplements", title: "Dietary Supplements Market Size Report", publisher: "Grand View Research", year: "2026", url: "https://www.grandviewresearch.com/industry-analysis/dietary-supplements-market-report", sourceType: "market" },
  { id: "who-tcim-2025", title: "Global Traditional Medicine Strategy 2025–2034", publisher: "World Health Organization", year: "2025", url: "https://www.who.int/teams/integrated-health-services/traditional-complementary-and-integrative-medicine/global-strategies", sourceType: "traditional" },
  { id: "ccras", title: "Clinical Research in Ayurvedic Sciences", publisher: "CCRAS (India)", year: "2026", url: "https://ccras.nic.in/services/clinical-research/", sourceType: "traditional" },
  { id: "ema-hmpc", title: "EU herbal monographs & list entries", publisher: "European Medicines Agency (HMPC)", year: "2026", url: "https://www.ema.europa.eu/en/human-regulatory-overview/herbal-medicinal-products", sourceType: "traditional" },
  { id: "tga", title: "Supporting claims and indications for listed medicines", publisher: "Therapeutic Goods Administration (Australia)", year: "2026", url: "https://www.tga.gov.au/evidence-guidelines", sourceType: "traditional" },
  { id: "health-canada-nhp", title: "Natural Health Products compendium of monographs", publisher: "Health Canada", year: "2026", url: "https://www.canada.ca/en/health-canada/services/drugs-health-products/natural-health-products-canada.html", sourceType: "traditional" },
  { id: "pcimh", title: "Indian medicine pharmacopoeial standards", publisher: "PCIMH", year: "2026", url: "https://www.pcimh.gov.in/", sourceType: "traditional" },
  { id: "nsf", title: "Supplement & Vitamin Certification", publisher: "NSF", year: "2026", url: "https://www.nsf.org/consumer-resources/articles/supplement-vitamin-certification", sourceType: "quality" },
  { id: "nutrients-ferroptosis-2025", title: "Ferroptosis, Nrf2/GPX4 and β-cell protection", publisher: "Nutrients (peer-reviewed)", year: "2025", url: "https://www.mdpi.com/journal/nutrients", sourceType: "research" },
  { id: "vasi-nigella-rct", title: "Topical Nigella sativa in vitiligo (RCT, VASI 4.98→3.75)", publisher: "Randomized clinical trial", year: "2024", url: "#", sourceType: "research" },
];

// ─────────────────────────────── Experts ───────────────────────────────
export const experts: Expert[] = [
  { id: "meera-iyer", name: "Dr. Meera Iyer", role: "Ayurveda protocol reviewer", location: "Bengaluru, India", credentials: ["BAMS", "12 yrs clinical Ayurveda"], specialties: ["Prakriti-informed diet charts", "Skin & pigmentation", "Women's wellness"], price: 99, turnaround: "24–48 hours" },
  { id: "arjun-menon", name: "Arjun Menon", role: "Yoga & breathwork therapist", location: "Kerala, India", credentials: ["RYT-500", "Pranayama specialist"], specialties: ["HPA-axis routines", "Sleep wind-down", "Adherence plans"], price: 69, turnaround: "24 hours" },
  { id: "nisha-rao", name: "Nisha Rao", role: "Holistic nutrition chart specialist", location: "Mumbai, India", credentials: ["MSc Nutrition", "Ayurveda diet integration"], specialties: ["Weight", "Blood sugar support", "Gut reset"], price: 89, turnaround: "24–48 hours" },
];

// ─────────────────────────────── Bundles ───────────────────────────────
export const bundles: Bundle[] = [
  {
    id: "skin-resilience-90", name: "90-Day Skin Resilience Pack", duration: "90 days", categoryId: "skin-pigmentation",
    price: 229, subscriptionPrice: 189, marginModel: "Reseller · 42% gross margin",
    summary: "Antioxidant, gut-skin and stress layers, COA-screened, mapped to the vitiligo golden journey.",
    products: [
      { name: "Broccoli Sprout Nrf2 Complex", supplier: "Verified reseller", role: "Nrf2 / antioxidant layer", format: "Capsule", price: 42, qualityScore: 91, qualitySignals: ["Sulforaphane standardized", "Third-party tested", "Heavy-metal screened"], evidenceGrade: "C" },
      { name: "Gut-Skin Probiotic", supplier: "Verified reseller", role: "Gut-skin axis", format: "Capsule", price: 38, qualityScore: 88, qualitySignals: ["Strain-verified", "CFU guaranteed to expiry"], evidenceGrade: "B" },
      { name: "Magnesium Glycinate Calm", supplier: "Verified reseller", role: "Stress-shield layer", format: "Capsule", price: 26, qualityScore: 93, qualitySignals: ["Chelated form", "USP-grade", "Low excipient"], evidenceGrade: "B" },
    ],
    includes: ["Daily companion schedule", "Diet & trigger tracker", "Evidence refresh feed", "Optional expert chart"],
  },
  { id: "metabolic-starter-60", name: "60-Day Metabolic Starter Pack", duration: "60 days", categoryId: "weight-metabolism", price: 149, subscriptionPrice: 119, marginModel: "Mixed resale + affiliate · 36%", summary: "Protein-first satiety and fiber, with meal-timing and walking routines.", products: [ { name: "Clean Protein Builder", supplier: "Verified reseller", role: "Satiety + muscle", format: "Powder", price: 54, qualityScore: 90, qualitySignals: ["Heavy-metal tested", "No proprietary blend"], evidenceGrade: "A" }, { name: "Soluble Fiber Meal Primer", supplier: "Verified reseller", role: "Glucose / fullness", format: "Powder", price: 24, qualityScore: 86, qualitySignals: ["Single-ingredient", "Allergen-clear"], evidenceGrade: "B" } ], includes: ["Meal-sequencing cards", "Post-meal walk reminders", "Weekly check-in"] },
  { id: "hair-density-90", name: "90-Day Hair Density Routine", duration: "90 days", categoryId: "hair-scalp", price: 199, subscriptionPrice: 169, marginModel: "Reseller · 45% gross margin", summary: "Scalp care, nutrient sufficiency and stress control for visible routine discipline.", products: [ { name: "Rosemary Scalp Serum", supplier: "Verified reseller", role: "Scalp topical", format: "Topical", price: 36, qualityScore: 87, qualitySignals: ["Patch-test guidance", "Fragrance-light"], evidenceGrade: "C" }, { name: "Protein Collagen Builder", supplier: "Verified reseller", role: "Nutrient foundation", format: "Powder", price: 46, qualityScore: 89, qualitySignals: ["Tested for contaminants"], evidenceGrade: "B" } ], includes: ["Shedding log", "Micronutrient testing checklist", "Scalp schedule"] },
  { id: "gut-reset-30", name: "30-Day Gut Reset", duration: "30 days", categoryId: "gut-bloating", price: 89, subscriptionPrice: 69, marginModel: "Reseller · 40% gross margin", summary: "Probiotic, enzyme and ginger with a structured trigger workflow.", products: [ { name: "Multi-Strain Gut Daily", supplier: "Verified reseller", role: "Microbiome", format: "Capsule", price: 38, qualityScore: 88, qualitySignals: ["Strain-verified", "CFU to expiry"], evidenceGrade: "B" }, { name: "Meal Enzyme Complex", supplier: "Verified reseller", role: "Digestive support", format: "Capsule", price: 29, qualityScore: 82, qualitySignals: ["Allergen-clear"], evidenceGrade: "C" } ], includes: ["Food reintroduction guide", "Bloating tracker", "Day-30 rotate prompt"] },
  { id: "stress-shield-monthly", name: "Monthly Stress Shield", duration: "30 days", categoryId: "sleep-stress", price: 74, subscriptionPrice: 59, marginModel: "Subscription · 48% gross margin", summary: "Calm nutrients plus routine cards and a weekly stress score.", products: [ { name: "Magnesium Glycinate Calm", supplier: "Verified reseller", role: "Relaxation", format: "Capsule", price: 26, qualityScore: 93, qualitySignals: ["Chelated", "USP-grade"], evidenceGrade: "B" }, { name: "L-Theanine Calm Focus", supplier: "Verified reseller", role: "Calm focus", format: "Capsule", price: 22, qualityScore: 90, qualitySignals: ["Single-ingredient"], evidenceGrade: "C" } ], includes: ["Breathwork routine", "Wind-down cards", "Weekly stress score"] },
  { id: "glucose-steady-60", name: "60-Day Glucose Steady Pack", duration: "60 days", categoryId: "blood-sugar", price: 129, subscriptionPrice: 99, marginModel: "Guarded · 34% · expert gate", summary: "Fiber, magnesium and meal sequencing — gated behind a medication safety review.", products: [ { name: "Soluble Fiber Meal Primer", supplier: "Verified reseller", role: "Post-meal glucose", format: "Powder", price: 24, qualityScore: 86, qualitySignals: ["Single-ingredient"], evidenceGrade: "B" }, { name: "Magnesium Glycinate Calm", supplier: "Verified reseller", role: "Insulin sensitivity", format: "Capsule", price: 26, qualityScore: 93, qualitySignals: ["Chelated"], evidenceGrade: "B" } ], includes: ["Meal-sequencing protocol", "Expert review gate", "Hypoglycemia safety card"] },
  { id: "mental-calm-30", name: "30-Day Calm Foundation", duration: "30 days", categoryId: "mental-wellbeing", price: 79, subscriptionPrice: 59, marginModel: "Subscription · 46% gross margin", summary: "Non-sedating calm support with crisis routing built in.", products: [ { name: "Magnesium Glycinate Calm", supplier: "Verified reseller", role: "Calm foundation", format: "Capsule", price: 26, qualityScore: 93, qualitySignals: ["Chelated"], evidenceGrade: "B" }, { name: "L-Theanine Calm Focus", supplier: "Verified reseller", role: "Stress reactivity", format: "Capsule", price: 22, qualityScore: 90, qualitySignals: ["Single-ingredient"], evidenceGrade: "C" } ], includes: ["Wellbeing check-ins", "Crisis routing card", "Routine builder"] },
  { id: "brain-focus-60", name: "60-Day Brain Focus Stack", duration: "60 days", categoryId: "brain-focus", price: 139, subscriptionPrice: 109, marginModel: "Reseller · 39% gross margin", summary: "Creatine and omega-3 with stimulant discipline.", products: [ { name: "Creatine Monohydrate Pure", supplier: "Verified reseller", role: "Cellular energy", format: "Powder", price: 29, qualityScore: 92, qualitySignals: ["Creapure-grade", "Single-ingredient"], evidenceGrade: "B" }, { name: "Omega-3 Brain Oil", supplier: "Verified reseller", role: "Cognitive support", format: "Softgel", price: 42, qualityScore: 88, qualitySignals: ["Oxidation-tested", "Heavy-metal screened"], evidenceGrade: "B" } ], includes: ["Focus routine", "Caffeine-timing cards", "Work-output review"] },
  { id: "tinnitus-quiet-90", name: "90-Day Tinnitus Quiet Pack", duration: "90 days", categoryId: "brain-focus", price: 169, subscriptionPrice: 139, marginModel: "Reseller · 41% gross margin", summary: "Tebonin Ginkgo + magnesium glycinate + zinc-balance + B12 methylcobalamin + Bhramari breath cards + sound-therapy app guidance.", products: [ { name: "Tebonin Ginkgo EGb 761", supplier: "Schwabe (EMA-monograph)", role: "Cochlear circulation + neuroplasticity", format: "Tablet", price: 49, qualityScore: 94, qualitySignals: ["EMA HMPC monograph", "Standardised EGb 761"], evidenceGrade: "B" }, { name: "Magnesium Glycinate Calm", supplier: "Verified reseller", role: "NMDA / glutamate excitotoxicity protection", format: "Capsule", price: 26, qualityScore: 93, qualitySignals: ["Chelated", "USP-grade"], evidenceGrade: "B" }, { name: "Zinc Balance Complex", supplier: "Verified reseller", role: "Cofactor (test ferritin/zinc first)", format: "Capsule", price: 24, qualityScore: 87, qualitySignals: ["Chelated", "Copper-balanced"], evidenceGrade: "C" }, { name: "B12 Methylcobalamin", supplier: "Verified reseller", role: "Auditory-nerve neurotrophic", format: "Sublingual", price: 22, qualityScore: 90, qualitySignals: ["Methylated form"], evidenceGrade: "C" } ], includes: ["Bhramari pranayama cards", "Sound-therapy app guidance (myNoise, Tinnitracks)", "Cervical / TMJ release routine", "DTC TFI score template"] },
  { id: "screen-eye-60", name: "60-Day Screen Eye Support", duration: "60 days", categoryId: "eye-screen", price: 119, subscriptionPrice: 89, marginModel: "Reseller · 37% gross margin", summary: "Carotenoids and omega-3 with break reminders and red-flag routing.", products: [ { name: "Lutein Zeaxanthin Vision Complex", supplier: "Verified reseller", role: "Macular pigment", format: "Softgel", price: 34, qualityScore: 89, qualitySignals: ["Standardized carotenoids"], evidenceGrade: "B" }, { name: "Omega-3 Eye Comfort Oil", supplier: "Verified reseller", role: "Tear-film comfort", format: "Softgel", price: 42, qualityScore: 88, qualitySignals: ["Oxidation-tested"], evidenceGrade: "C" } ], includes: ["20-20-20 break reminders", "Lighting hygiene", "Specialist red-flag card"] },
  { id: "mobility-core-90", name: "90-Day Mobility Core", duration: "90 days", categoryId: "joints-mobility", price: 179, subscriptionPrice: 139, marginModel: "Reseller · 41% gross margin", summary: "Collagen, curcumin and omega with strength habits.", products: [ { name: "Collagen Peptide Builder", supplier: "Verified reseller", role: "Connective tissue", format: "Powder", price: 45, qualityScore: 88, qualitySignals: ["Hydrolyzed", "Tested"], evidenceGrade: "B" }, { name: "Curcumin Phytosome Comfort", supplier: "Verified reseller", role: "Inflammatory balance", format: "Capsule", price: 39, qualityScore: 86, qualitySignals: ["Bioavailable phytosome"], evidenceGrade: "B" } ], includes: ["Strength habit cards", "Comfort trend log"] },
  { id: "midlife-balance-60", name: "60-Day Midlife Balance", duration: "60 days", categoryId: "women-hormone", price: 159, subscriptionPrice: 129, marginModel: "Expert-assisted · 35%", summary: "Sleep, protein and conservative botanicals with an expert chart option.", products: [ { name: "Magnesium Glycinate Calm", supplier: "Verified reseller", role: "Sleep / heat", format: "Capsule", price: 26, qualityScore: 93, qualitySignals: ["Chelated"], evidenceGrade: "B" }, { name: "Sage Comfort Extract", supplier: "Verified reseller", role: "Menopause comfort", format: "Capsule", price: 38, qualityScore: 84, qualitySignals: ["Standardized"], evidenceGrade: "T" } ], includes: ["Sleep/heat review", "Strength routine", "Expert chart point"] },
  { id: "vitality-core-60", name: "60-Day Vitality Core", duration: "60 days", categoryId: "mens-vitality", price: 149, subscriptionPrice: 119, marginModel: "Guarded subscription · 38%", summary: "Mineral sufficiency and sleep support with firm red-flag routing.", products: [ { name: "Zinc Balance Complex", supplier: "Verified reseller", role: "Mineral sufficiency", format: "Capsule", price: 24, qualityScore: 87, qualitySignals: ["Chelated", "Copper-balanced"], evidenceGrade: "B" }, { name: "Magnesium Glycinate Calm", supplier: "Verified reseller", role: "Sleep / stress", format: "Capsule", price: 26, qualityScore: 93, qualitySignals: ["Chelated"], evidenceGrade: "B" } ], includes: ["Red-flag screen", "Strength routine", "Expert escalation"] },
  { id: "recovery-engine-60", name: "60-Day Recovery Engine", duration: "60 days", categoryId: "energy-recovery", price: 129, subscriptionPrice: 99, marginModel: "High-retention subscription · 43% GM", summary: "Protein, creatine and electrolytes with COAs.", products: [ { name: "Clean Protein Builder", supplier: "Verified reseller", role: "Recovery", format: "Powder", price: 54, qualityScore: 90, qualitySignals: ["No proprietary blend"], evidenceGrade: "A" }, { name: "Creatine Monohydrate Pure", supplier: "Verified reseller", role: "Training output", format: "Powder", price: 29, qualityScore: 92, qualitySignals: ["Creapure-grade"], evidenceGrade: "B" } ], includes: ["Recovery rhythm cards", "Hydration routine", "COA links"] },
];

// ─────────────────────── Companion daily timeline ───────────────────────
export const companionEvents: CompanionEvent[] = [
  { time: "7:30 AM", title: "Morning anchor", detail: "Antioxidant / protein layer after breakfast. Log digestion if new.", type: "supplement" },
  { time: "12:30 PM", title: "Meal intelligence", detail: "Protein and fiber first, colourful plants, trigger tracking.", type: "diet" },
  { time: "6:30 PM", title: "Post-meal reset", detail: "10-minute walk, or two-minute breathing if stress is high.", type: "routine" },
  { time: "8:45 PM", title: "Evening support", detail: "Magnesium / theanine or gut support after dinner.", type: "supplement" },
  { time: "Friday", title: "Weekly check-in", detail: "Tolerance, adherence, symptom trend, expert-review need.", type: "checkin" },
  { time: "Day 75", title: "Refill decision", detail: "Continue, pause, adjust, or ask an expert before the next cycle.", type: "refill" },
];

// ─────────────────────────── Factory jobs ───────────────────────────────
export const factoryJobs: FactoryJob[] = [
  { id: "job-skin", categoryId: "skin-pigmentation", status: "fresh", cadence: "Monthly w/ expert review", lastRun: "2026-05-03", nextRun: "2026-06-03", sourcesScanned: 128, claimsExtracted: 31, safetyFlags: 6, reviewer: "Skin evidence reviewer" },
  { id: "job-weight", categoryId: "weight-metabolism", status: "current", cadence: "Weekly / monthly", lastRun: "2026-04-27", nextRun: "2026-05-10", sourcesScanned: 214, claimsExtracted: 44, safetyFlags: 9, reviewer: "Metabolic safety reviewer" },
  { id: "job-hair", categoryId: "hair-scalp", status: "fresh", cadence: "Monthly w/ scalp safety", lastRun: "2026-05-03", nextRun: "2026-06-03", sourcesScanned: 104, claimsExtracted: 23, safetyFlags: 6, reviewer: "Hair & scalp reviewer" },
  { id: "job-gut", categoryId: "gut-bloating", status: "fresh", cadence: "Monthly", lastRun: "2026-05-02", nextRun: "2026-06-02", sourcesScanned: 93, claimsExtracted: 22, safetyFlags: 4, reviewer: "Microbiome reviewer" },
  { id: "job-sleep", categoryId: "sleep-stress", status: "review_required", cadence: "Monthly", lastRun: "2026-05-01", nextRun: "2026-05-08", sourcesScanned: 101, claimsExtracted: 28, safetyFlags: 11, reviewer: "Mood / safety reviewer" },
  { id: "job-sugar", categoryId: "blood-sugar", status: "review_required", cadence: "Weekly safety scan", lastRun: "2026-05-03", nextRun: "2026-05-10", sourcesScanned: 137, claimsExtracted: 31, safetyFlags: 16, reviewer: "Glucose & medication reviewer" },
  { id: "job-mental", categoryId: "mental-wellbeing", status: "review_required", cadence: "Weekly safety scan", lastRun: "2026-05-03", nextRun: "2026-05-10", sourcesScanned: 146, claimsExtracted: 33, safetyFlags: 15, reviewer: "Mental wellbeing reviewer" },
  { id: "job-brain", categoryId: "brain-focus", status: "current", cadence: "Monthly", lastRun: "2026-05-02", nextRun: "2026-06-02", sourcesScanned: 118, claimsExtracted: 27, safetyFlags: 7, reviewer: "Cognition reviewer" },
  { id: "job-eye", categoryId: "eye-screen", status: "current", cadence: "Monthly w/ red-flag review", lastRun: "2026-05-02", nextRun: "2026-06-02", sourcesScanned: 74, claimsExtracted: 18, safetyFlags: 8, reviewer: "Eye nutrition reviewer" },
  { id: "job-joints", categoryId: "joints-mobility", status: "fresh", cadence: "Monthly", lastRun: "2026-05-03", nextRun: "2026-06-03", sourcesScanned: 96, claimsExtracted: 21, safetyFlags: 5, reviewer: "Mobility reviewer" },
  { id: "job-hormone", categoryId: "women-hormone", status: "review_required", cadence: "Weekly safety scan", lastRun: "2026-05-03", nextRun: "2026-05-10", sourcesScanned: 132, claimsExtracted: 29, safetyFlags: 14, reviewer: "Women's wellness reviewer" },
  { id: "job-vitality", categoryId: "mens-vitality", status: "review_required", cadence: "Weekly safety scan", lastRun: "2026-05-03", nextRun: "2026-05-10", sourcesScanned: 121, claimsExtracted: 25, safetyFlags: 12, reviewer: "Men's vitality reviewer" },
  { id: "job-energy", categoryId: "energy-recovery", status: "fresh", cadence: "Monthly", lastRun: "2026-05-03", nextRun: "2026-06-03", sourcesScanned: 109, claimsExtracted: 24, safetyFlags: 4, reviewer: "Sports nutrition reviewer" },
];

// ───────────────────────── 50-journey atlas ─────────────────────────────
export const journeys: Journey[] = [
  // Skin (6)
  { id: "vitiligo-support", name: "Vitiligo Support", domain: "Skin", route: "/skin/vitiligo", consumerHook: "Honest vitiligo support — no snake-oil repigmentation.", packageConcept: "90-day Skin Resilience Pack: COA antioxidants + gut + stress.", gradeMix: ["B", "C", "D", "T"], freshness: "fresh", risk: "moderate" },
  { id: "acne-prone-skin", name: "Acne-Prone Skin Routine", domain: "Skin", route: "/skin/acne-prone", consumerHook: "Fewer flare triggers, a calm non-harsh routine.", packageConcept: "Clear Skin Foundations: probiotic + zinc-balanced + barrier.", gradeMix: ["B", "C"], freshness: "current", risk: "low" },
  { id: "eczema-prone-skin", name: "Eczema-Prone Skin Comfort", domain: "Skin", route: "/skin/eczema-prone", consumerHook: "Itch and dryness support without irritation.", packageConcept: "Barrier Calm Pack: gentle oils + probiotic option + tools.", gradeMix: ["C", "T"], freshness: "current", risk: "moderate" },
  { id: "psoriasis-prone-skin", name: "Psoriasis-Prone Skin Support", domain: "Skin", route: "/skin/psoriasis-prone", consumerHook: "Inflammation-aware support, not a care replacement.", packageConcept: "Skin Inflammation Support: omega + curcumin + stress shield.", gradeMix: ["B", "C", "D"], freshness: "current", risk: "guarded" },
  { id: "melasma-hyperpigmentation", name: "Melasma & Hyperpigmentation", domain: "Skin", route: "/skin/hyperpigmentation", consumerHook: "A pigmentation routine that explains what's realistic.", packageConcept: "Pigment Balance Pack: antioxidant + topical checklist.", gradeMix: ["C", "D"], freshness: "current", risk: "low" },
  { id: "skin-aging-collagen", name: "Skin Aging & Collagen", domain: "Skin", route: "/skin/collagen-aging", consumerHook: "Firmer-looking skin that fits daily life.", packageConcept: "Beauty From Within: collagen + antioxidant foods + checks.", gradeMix: ["B", "C"], freshness: "current", risk: "low" },
  { id: "rosacea-redness", name: "Rosacea & Facial Redness", domain: "Skin", route: "/skin/rosacea", consumerHook: "Rosacea support that respects barrier-first OTC reality.", packageConcept: "Rosacea Calm Pack: niacinamide + azelaic acid + green tea polyphenols + trigger-map + gentle barrier routine.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "moderate" },
  // Hair (4)
  { id: "hair-thinning-density", name: "Hair Thinning & Density", domain: "Hair", route: "/hair/thinning", consumerHook: "Reduce shedding anxiety with a real scalp/nutrition routine.", packageConcept: "90-day Hair Density Routine: topical scalp + nutrition.", gradeMix: ["C", "B"], freshness: "fresh", risk: "moderate" },
  { id: "stress-shedding", name: "Stress Shedding Support", domain: "Hair", route: "/hair/stress-shedding", consumerHook: "Shedding worse after stress — a calming routine.", packageConcept: "Stress Shedding Reset: calm stack + protein + scalp schedule.", gradeMix: ["C", "B"], freshness: "current", risk: "low" },
  { id: "dandruff-scalp-comfort", name: "Dandruff & Scalp Comfort", domain: "Hair", route: "/hair/scalp-comfort", consumerHook: "Less scalp irritation with a simple routine.", packageConcept: "Scalp Calm Kit: topical routine + tested oils + nutrition.", gradeMix: ["C", "T"], freshness: "current", risk: "low" },
  { id: "premature-greying", name: "Premature Greying Support", domain: "Hair", route: "/hair/premature-greying", consumerHook: "Nutrient/stress factors — no fake reversal claims.", packageConcept: "Hair Vitality Foundations: antioxidant nutrition + testing.", gradeMix: ["D", "T"], freshness: "current", risk: "low" },
  // Metabolic (5)
  { id: "weight-belly-fat", name: "Weight & Belly Fat", domain: "Metabolic", route: "/weight/belly-fat", consumerHook: "Belly-fat support starting with protein, fiber, sleep, walking.", packageConcept: "60-day Metabolic Starter: protein + fiber + coaching.", gradeMix: ["A", "B"], freshness: "current", risk: "guarded" },
  { id: "glp1-maintenance", name: "GLP-1 Maintenance Nutrition", domain: "Metabolic", route: "/weight/glp1-maintenance", consumerHook: "On or coming off GLP-1 — protect muscle and routine.", packageConcept: "GLP-1 Nutrition Companion: protein + fiber + tolerance.", gradeMix: ["A", "B"], freshness: "current", risk: "guarded" },
  { id: "cravings-emotional-eating", name: "Cravings & Emotional Eating", domain: "Metabolic", route: "/weight/cravings", consumerHook: "Fewer evening cravings — no stimulants, no shame.", packageConcept: "Craving Reset Pack: protein/fiber + calm stack + coaching.", gradeMix: ["B", "C"], freshness: "current", risk: "low" },
  { id: "blood-sugar-support", name: "Blood Sugar Support", domain: "Metabolic", route: "/metabolic/blood-sugar", consumerHook: "Food-first glucose support, no unsafe medication advice.", packageConcept: "60-day Glucose Steady: fiber + magnesium + expert gate.", gradeMix: ["B"], freshness: "review_required", risk: "specialist" },
  { id: "insulin-resistance-support", name: "Insulin Resistance Support", domain: "Metabolic", route: "/metabolic/insulin-resistance", consumerHook: "Practical insulin-sensitivity support via habits.", packageConcept: "Insulin Rhythm Pack: food plan + fiber + expert upgrade.", gradeMix: ["B", "C"], freshness: "review_required", risk: "guarded" },
  { id: "type-2-diabetes-active", name: "Type 2 Diabetes (active management)", domain: "Metabolic", route: "/metabolic/type-2-diabetes", consumerHook: "Honest adjunct for users already on T2D medication.", packageConcept: "T2D Companion Pack: fiber + magnesium + CGM-paired routine.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "type-1-diabetes-adjunct", name: "Type 1 Diabetes Adjunct", domain: "Metabolic", route: "/metabolic/type-1-diabetes", consumerHook: "T1D adjunctive: nutrient cofactors + CGM coaching — never replaces insulin.", packageConcept: "T1D Adjunct Pack: Mg + B-vits + vit D + omega-3 + chromium null surfaced + CGM-pattern coaching.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  // Gut (5)
  { id: "gut-bloating", name: "Gut Bloating", domain: "Gut", route: "/gut/bloating", consumerHook: "A calm stomach routine — no probiotic roulette.", packageConcept: "30-day Gut Reset: probiotic + enzyme + trigger workflow.", gradeMix: ["B", "C"], freshness: "fresh", risk: "moderate" },
  { id: "constipation-regularity", name: "Constipation & Regularity", domain: "Gut", route: "/gut/regularity", consumerHook: "Gentle regularity without harsh-laxative dependence.", packageConcept: "Gentle Regularity Pack: fiber + magnesium + hydration.", gradeMix: ["B"], freshness: "current", risk: "low" },
  { id: "reflux-support", name: "Reflux Support", domain: "Gut", route: "/gut/reflux", consumerHook: "Meal and trigger support for reflux, no risky advice.", packageConcept: "Reflux Rhythm Pack: meal timing + trigger journal.", gradeMix: ["C", "T"], freshness: "current", risk: "moderate" },
  { id: "ibs-like-patterns", name: "IBS-Like Pattern Support", domain: "Gut", route: "/gut/ibs-like", consumerHook: "A structured way to test foods and calm the gut.", packageConcept: "IBS Pattern Kit: probiotic + fiber matching + guide.", gradeMix: ["B", "C"], freshness: "current", risk: "guarded" },
  { id: "microbiome-reset", name: "Microbiome Reset", domain: "Gut", route: "/gut/microbiome-reset", consumerHook: "Rebuild the gut after travel, diet chaos, antibiotics.", packageConcept: "30-day Microbiome Reset: probiotic + prebiotic + plan.", gradeMix: ["B", "C"], freshness: "fresh", risk: "low" },
  { id: "ibd-crohns-uc", name: "Inflammatory Bowel Disease (Crohn's & UC)", domain: "Gut", route: "/gut/ibd", consumerHook: "IBD adjunctive support: omega-3, curcumin — alongside your biologics.", packageConcept: "IBD Adjunct Pack: omega-3 EPA + curcumin Lang 2015 UC + AKBA-Boswellia + low-FODMAP guide.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  // StressSleep (7)
  { id: "sleep-onset", name: "Sleep Onset Support", domain: "StressSleep", route: "/sleep/onset", consumerHook: "Can't fall asleep — a non-hype wind-down protocol.", packageConcept: "Sleep Onset Pack: magnesium + glycine/theanine + cards.", gradeMix: ["B", "C"], freshness: "current", risk: "moderate" },
  { id: "night-waking", name: "Night Waking Support", domain: "StressSleep", route: "/sleep/night-waking", consumerHook: "Wake at 2–4 AM — understand the pattern.", packageConcept: "Night Reset Pack: calm stack + evening nutrition prompts.", gradeMix: ["B", "C"], freshness: "current", risk: "moderate" },
  { id: "stress-cortisol-balance", name: "Stress & Cortisol Balance", domain: "StressSleep", route: "/stress/cortisol", consumerHook: "Wired and tired — a safer calm routine.", packageConcept: "Stress Shield Pack: calm nutrients + routine cards + score.", gradeMix: ["B", "C"], freshness: "fresh", risk: "moderate" },
  { id: "burnout-recovery", name: "Burnout Recovery", domain: "StressSleep", route: "/stress/burnout", consumerHook: "Energy back without stimulant stacking.", packageConcept: "Burnout Recovery Pack: energy nutrition + calm stack.", gradeMix: ["B", "C"], freshness: "current", risk: "guarded" },
  { id: "anxiety-like-calm", name: "Anxiety-Like Calm Support", domain: "StressSleep", route: "/stress/calm", consumerHook: "Feel calmer — no 'supplement fixes anxiety' nonsense.", packageConcept: "Calm Foundation Pack: non-sedating support + routing.", gradeMix: ["C", "D"], freshness: "review_required", risk: "guarded" },
  { id: "low-mood-support", name: "Low Mood Support", domain: "StressSleep", route: "/mood/low-mood", consumerHook: "Low-mood support with clear safety and escalation.", packageConcept: "Mood Foundation Pack: omega/calm support + check-ins.", gradeMix: ["C", "D"], freshness: "review_required", risk: "specialist" },
  { id: "emotional-eating", name: "Emotional Eating Support", domain: "StressSleep", route: "/mood/emotional-eating", consumerHook: "A plan for stress eating, not blame.", packageConcept: "Emotional Eating Reset: meal anchors + calm stack.", gradeMix: ["B", "C"], freshness: "current", risk: "low" },
  { id: "ocd-adjunctive", name: "OCD Adjunctive Support", domain: "StressSleep", route: "/mood/ocd", consumerHook: "OCD support beyond just meds — NAC has real evidence specifically for OCD.", packageConcept: "OCD Foundations Pack: NAC 2-3g Sayyah 2012 + inositol Fux 1996 + ERP behavioural A-grade.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "caregiver-burnout", name: "Caregiver Burnout (family + spouse)", domain: "StressSleep", route: "/mood/caregiver-burnout", consumerHook: "Specific to family + spouse caregivers — respite-care + grief + guilt + MBSR.", packageConcept: "Caregiver Survival Pack: respite-care nav + MBSR Whitebird 2013 + caregiver-specific peer support + sleep priority.", gradeMix: ["B", "C"], freshness: "fresh", risk: "moderate" },
  // BrainEye (6) — tinnitus added
  { id: "tinnitus-support", name: "Tinnitus Support", domain: "BrainEye", route: "/ears/tinnitus", consumerHook: "Quieter ears — neuroplastic and circulatory support, no false promises.", packageConcept: "90-day Tinnitus Quiet: magnesium + Ginkgo (Tebonin EMA) + zinc + sound therapy + breathwork.", gradeMix: ["B", "C", "T", "H"], freshness: "fresh", risk: "moderate" },
  { id: "brain-fog-focus", name: "Brain Fog & Focus", domain: "BrainEye", route: "/brain/focus", consumerHook: "Clearer focus without overdoing caffeine.", packageConcept: "60-day Brain Focus Stack: creatine + omega-3.", gradeMix: ["B", "C"], freshness: "current", risk: "moderate" },
  { id: "memory-aging", name: "Memory & Brain Aging", domain: "BrainEye", route: "/brain/memory-aging", consumerHook: "Support memory and the aging brain realistically.", packageConcept: "Memory Aging Pack: omega-3 + creatine + habit tracking.", gradeMix: ["B", "C"], freshness: "current", risk: "moderate" },
  { id: "screen-eye-strain", name: "Screen Eye Strain", domain: "BrainEye", route: "/eyes/screen-strain", consumerHook: "Tired eyes from screens — daily support.", packageConcept: "60-day Screen Eye Support: carotenoids + omega-3.", gradeMix: ["B", "C"], freshness: "current", risk: "guarded" },
  { id: "dry-eye-comfort", name: "Dry Eye Comfort", domain: "BrainEye", route: "/eyes/dry-eye", consumerHook: "Dry-eye comfort and better screen habits.", packageConcept: "Dry Eye Comfort Pack: omega support + screen routine.", gradeMix: ["C"], freshness: "current", risk: "moderate" },
  { id: "macular-support", name: "Macular Support", domain: "BrainEye", route: "/eyes/macular-support", consumerHook: "Long-term eye nutrition — no eyesight-reversal claims.", packageConcept: "Macular Nutrition Pack: carotenoids + tested omega.", gradeMix: ["B", "C"], freshness: "current", risk: "guarded" },
  { id: "migraine-headache", name: "Migraine & Headache", domain: "BrainEye", route: "/brain/migraine", consumerHook: "Migraine relief that takes natural protocols seriously.", packageConcept: "Migraine Calm Pack: riboflavin 400mg + CoQ10 + magnesium + feverfew, with CGRP-class clinic-route.", gradeMix: ["A", "B", "T"], freshness: "fresh", risk: "moderate" },
  { id: "adult-adhd-support", name: "Adult ADHD Support", domain: "BrainEye", route: "/brain/adult-adhd", consumerHook: "Adult-ADHD support that respects both meds and natural levers.", packageConcept: "ADHD Foundations Pack: omega-3 EPA + iron + saffron + Pomodoro + body-doubling.", gradeMix: ["B", "C"], freshness: "fresh", risk: "moderate" },
  { id: "peripheral-neuropathy", name: "Peripheral Neuropathy", domain: "BrainEye", route: "/brain/peripheral-neuropathy", consumerHook: "Numbness + tingling that goes beyond just managing — real natural levers.", packageConcept: "Neuropathy Support Pack: ALA 600mg SYDNEY + benfotiamine + ALCAR + methylcobalamin.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "moderate" },
  { id: "stroke-recovery-adjunctive", name: "Stroke Recovery Adjunct", domain: "BrainEye", route: "/brain/stroke-recovery", consumerHook: "Post-stroke neuroplasticity nutrition — alongside your PT/OT/SLT team.", packageConcept: "Stroke Recovery Pack: citicoline ICTUS + omega-3 DHA + lion's mane + Mediterranean + structured rehab.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "vertigo-dizziness", name: "Vertigo & Dizziness", domain: "BrainEye", route: "/brain/vertigo", consumerHook: "Self-administered Epley + vestibular rehab apps for BPPV — gold-standard at home.", packageConcept: "Vertigo Reset Pack: Epley self-maneuver A-grade BPPV + vestibular-rehab apps + Mg + low-sodium Meniere context.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "moderate" },
  { id: "bells-palsy", name: "Bell's Palsy", domain: "BrainEye", route: "/brain/bells-palsy", consumerHook: "Acute facial-nerve weakness — 72-hour Rx window matters; recovery support after.", packageConcept: "Bell's Palsy Recovery Pack: B-complex + omega-3 + facial-PT (Kabat) + eye-protection + Rx-corticosteroid window context.", gradeMix: ["A", "B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "sshl-hearing-loss", name: "Sudden Sensorineural Hearing Loss (SSHL)", domain: "BrainEye", route: "/ears/sshl", consumerHook: "Audiology EMERGENCY — 72-hour steroid window. Adjunct recovery support after Rx.", packageConcept: "SSHL Recovery Pack: high-dose vit C + omega-3 + lipo-PGE1 context + intratympanic-steroid clinic-route + audiology urgent referral.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  // MobilityEnergy (5)
  { id: "joint-stiffness", name: "Joint Stiffness", domain: "MobilityEnergy", route: "/joints/stiffness", consumerHook: "Less morning stiffness with a followable routine.", packageConcept: "90-day Mobility Core: collagen + curcumin + strength.", gradeMix: ["B"], freshness: "fresh", risk: "moderate" },
  { id: "knee-mobility", name: "Knee Mobility Support", domain: "MobilityEnergy", route: "/joints/knee-mobility", consumerHook: "Knee comfort plus exercises and weight-aware habits.", packageConcept: "Knee Mobility Pack: collagen + botanicals + exercises.", gradeMix: ["B", "C"], freshness: "current", risk: "moderate" },
  { id: "tendon-recovery", name: "Tendon Recovery", domain: "MobilityEnergy", route: "/recovery/tendon", consumerHook: "Tendon support that respects healing time.", packageConcept: "Tendon Recovery Kit: collagen + protein + timing.", gradeMix: ["B", "C"], freshness: "current", risk: "moderate" },
  { id: "sports-recovery", name: "Sports Recovery", domain: "MobilityEnergy", route: "/recovery/sports", consumerHook: "Recovery and performance without sketchy blends.", packageConcept: "60-day Recovery Engine: protein + creatine + COAs.", gradeMix: ["A", "B"], freshness: "fresh", risk: "low" },
  { id: "daily-energy-fatigue", name: "Daily Energy & Fatigue", domain: "MobilityEnergy", route: "/energy/fatigue", consumerHook: "Better daily energy without stimulant dependence.", packageConcept: "Daily Energy Pack: protein/creatine/electrolytes.", gradeMix: ["A", "B"], freshness: "current", risk: "low" },
  { id: "osteoarthritis-systemic", name: "Osteoarthritis (systemic)", domain: "MobilityEnergy", route: "/joints/osteoarthritis", consumerHook: "OA support that takes weight + curcumin + collagen seriously.", packageConcept: "OA Mobility Pack: curcumin Bannuru A- + Boswellia + collagen + weight-loss IDEA A-grade.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "moderate" },
  { id: "osteoporosis-bone-density", name: "Osteoporosis & Bone Density", domain: "MobilityEnergy", route: "/joints/osteoporosis", consumerHook: "Bone-density preservation: nutrients + heavy-resistance, not pills alone.", packageConcept: "Bone Density Pack: D3 + K2 MK7 + Mg + calcium-from-food + LIFTMOR A-grade resistance.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "moderate" },
  { id: "fibromyalgia-chronic-pain", name: "Fibromyalgia & Chronic Widespread Pain", domain: "MobilityEnergy", route: "/joints/fibromyalgia", consumerHook: "Fibromyalgia support that doesn't dismiss the pain.", packageConcept: "Fibro Calm Pack: Mg malate + vit D + CoQ10 Cordero 2013 + CBT-CP + low-dose-naltrexone context.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "rheumatoid-arthritis-adjunct", name: "Rheumatoid Arthritis Adjunct", domain: "MobilityEnergy", route: "/joints/rheumatoid-arthritis", consumerHook: "RA adjunctive support — Mediterranean diet + omega-3 EPA alongside DMARDs.", packageConcept: "RA Calm Pack: omega-3 EPA 3g Goldberg meta + curcumin Daily 2016 + vit D + Mediterranean diet, with methotrexate/biologic context.", gradeMix: ["A", "B", "C", "T"], freshness: "fresh", risk: "specialist" },
  // HormoneVitality (7)
  { id: "pms-support", name: "PMS Support", domain: "HormoneVitality", route: "/women/pms", consumerHook: "Cycle comfort without dismissive advice.", packageConcept: "Cycle Comfort Pack: magnesium + omega + tracking.", gradeMix: ["B", "C"], freshness: "current", risk: "moderate" },
  { id: "pcos-support", name: "PCOS Support", domain: "HormoneVitality", route: "/women/pcos", consumerHook: "Insulin and cycle support with safety boundaries.", packageConcept: "PCOS Rhythm Pack: inositol + fiber/protein + chart.", gradeMix: ["B", "C"], freshness: "review_required", risk: "specialist" },
  { id: "menopause-perimenopause", name: "Perimenopause & Menopause", domain: "HormoneVitality", route: "/women/menopause", consumerHook: "Sleep, hot-flash, mood and strength support, not ignored.", packageConcept: "60-day Midlife Balance: sleep + protein + botanicals.", gradeMix: ["B", "T"], freshness: "current", risk: "guarded" },
  { id: "fertility-readiness", name: "Fertility Readiness", domain: "HormoneVitality", route: "/fertility/readiness", consumerHook: "Preconception nutrition that knows its limits.", packageConcept: "Fertility Readiness Pack: expert-reviewed chart.", gradeMix: ["B", "C"], freshness: "review_required", risk: "specialist" },
  { id: "mens-testosterone-vitality", name: "Men's Testosterone & Vitality", domain: "HormoneVitality", route: "/men/testosterone-vitality", consumerHook: "Vitality without dangerous testosterone claims.", packageConcept: "60-day Vitality Core: minerals + sleep + escalation.", gradeMix: ["B", "T"], freshness: "review_required", risk: "guarded" },
  { id: "libido-stamina", name: "Libido & Stamina Support", domain: "HormoneVitality", route: "/men/libido-stamina", consumerHook: "Stamina support that screens red flags first.", packageConcept: "Stamina Foundations Pack: mineral + stress + fitness.", gradeMix: ["C", "T"], freshness: "current", risk: "guarded" },
  { id: "prostate-wellness", name: "Prostate Wellness", domain: "HormoneVitality", route: "/men/prostate-wellness", consumerHook: "Urinary comfort support with clear red-flag routing.", packageConcept: "Prostate Comfort Pack: urinary botanicals + card.", gradeMix: ["C", "T"], freshness: "current", risk: "guarded" },
  { id: "hashimoto-hypothyroid", name: "Hashimoto's & Hypothyroid Support", domain: "HormoneVitality", route: "/thyroid/hashimoto-hypothyroid", consumerHook: "Honest support for slow thyroid — alongside your levothyroxine.", packageConcept: "Thyroid Foundation Pack: selenium 200mcg + zinc + vitamin D + Mg + AIP trial guide.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "uti-recurrence-prevention", name: "UTI Recurrence Prevention", domain: "HormoneVitality", route: "/urinary/uti-recurrence", consumerHook: "Stop the every-month UTI cycle with the protocol that has real evidence.", packageConcept: "UTI Prevention Pack: D-mannose 2g + cranberry PAC 36mg + L. crispatus + methenamine context.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "moderate" },
  { id: "endometriosis-natural", name: "Endometriosis Natural Support", domain: "HormoneVitality", route: "/women/endometriosis", consumerHook: "Endometriosis support that takes pain + NAC + curcumin seriously.", packageConcept: "Endo Calm Pack: NAC Porpora 2013 + curcumin + omega-3 EPA + Mg + anti-inflammatory diet.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "pregnancy-postpartum-nutrition", name: "Pregnancy & Postpartum Nutrition", domain: "HormoneVitality", route: "/women/pregnancy-postpartum", consumerHook: "Trimester-specific nutrition + postpartum recovery, evidence-graded.", packageConcept: "Pregnancy Foundation: folate + DHA + choline + iron + vit D + teratogen audit + postpartum depression screening.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "specialist" },
  { id: "kidney-stones-prevention", name: "Kidney Stones Prevention", domain: "HormoneVitality", route: "/urinary/kidney-stones", consumerHook: "Stop stone recurrence with hydration + citrate + the protocol with real evidence.", packageConcept: "Stone Prevention Pack: 2.5L hydration A-grade + K-citrate + Mg + oxalate-management + Ca-from-food guide.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "moderate" },
  // ImmuneOral (3)
  { id: "immune-allergy-comfort", name: "Immune & Allergy Comfort", domain: "ImmuneOral", route: "/immune/allergy-comfort", consumerHook: "Seasonal comfort without drowsy chaos.", packageConcept: "Seasonal Comfort Pack: quercetin + nettle + probiotic.", gradeMix: ["C", "D"], freshness: "current", risk: "low" },
  { id: "respiratory-seasonal", name: "Respiratory Seasonal Support", domain: "ImmuneOral", route: "/respiratory/seasonal", consumerHook: "Seasonal breathing comfort and an immune routine.", packageConcept: "Seasonal Respiratory Comfort: nutrient support + guide.", gradeMix: ["C", "T"], freshness: "current", risk: "guarded" },
  { id: "oral-gum-breath", name: "Oral, Gum & Breath Health", domain: "ImmuneOral", route: "/oral/gum-breath", consumerHook: "Fresher breath, gum support and better habits.", packageConcept: "Oral Microbiome Pack: oral probiotic + xylitol + tracker.", gradeMix: ["C", "B"], freshness: "current", risk: "low" },
  { id: "asthma-chronic-control", name: "Asthma (chronic control)", domain: "ImmuneOral", route: "/respiratory/asthma", consumerHook: "Asthma control: Buteyko + vit D + Mg, alongside your inhalers.", packageConcept: "Asthma Calm Pack: Buteyko Cochrane B+ + vit D Martineau A-grade + Mg + omega-3, with ICS context.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "guarded" },
  { id: "copd-natural-support", name: "COPD Natural Adjunct", domain: "ImmuneOral", route: "/respiratory/copd", consumerHook: "COPD adjunctive: NAC + pulmonary rehab + smoking cessation as the highest-lever intervention.", packageConcept: "COPD Adjunct Pack: NAC 600mg BD Cochrane BRONCUS-PANTHEON-BREATHE A-grade + vit D + Buteyko + smoking cessation primary lever.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "specialist" },
  // CardioLiverLongevity (3)
  { id: "heart-cholesterol-bp", name: "Heart, Cholesterol & BP", domain: "CardioLiverLongevity", route: "/heart/cholesterol-bp", consumerHook: "Food-first heart support, no risky medication advice.", packageConcept: "Heart Rhythm Support: fiber + omega + expert gate.", gradeMix: ["B", "C"], freshness: "review_required", risk: "specialist" },
  { id: "liver-alcohol-recovery", name: "Liver & Alcohol Recovery", domain: "CardioLiverLongevity", route: "/liver/alcohol-recovery", consumerHook: "Liver-support habits after alcohol — no fake detox.", packageConcept: "Liver Recovery Habits: hydration + nutrient + plan.", gradeMix: ["C", "T"], freshness: "current", risk: "guarded" },
  { id: "longevity-healthy-aging", name: "Longevity & Healthy Aging", domain: "CardioLiverLongevity", route: "/longevity/healthy-aging", consumerHook: "A longevity routine based on basics, not exotic hype.", packageConcept: "Healthy Aging Core: protein + omega + fiber + dashboard.", gradeMix: ["A", "B"], freshness: "current", risk: "low" },
  { id: "nafld-mash-fatty-liver", name: "NAFLD / MASH (Fatty Liver)", domain: "CardioLiverLongevity", route: "/liver/nafld-mash", consumerHook: "Honest natural support for fatty liver — the world's most prevalent liver disease.", packageConcept: "NAFLD Reset Pack: vit E 400IU PIVENS + silymarin + berberine + Mediterranean diet, with Rezdiffra context.", gradeMix: ["A", "B", "C"], freshness: "fresh", risk: "specialist" },
  { id: "afib-natural-adjunct", name: "Atrial Fibrillation Natural Adjunct", domain: "CardioLiverLongevity", route: "/heart/afib", consumerHook: "AFib adjunctive support: Mg taurate + K2 + omega-3 — alongside your DOAC.", packageConcept: "AFib Calm Pack: Mg taurate B-grade + K2 MK7 + omega-3 + HRV biofeedback, with anticoagulation context.", gradeMix: ["B", "C", "T"], freshness: "fresh", risk: "specialist" },
  { id: "chronic-venous-insufficiency", name: "Chronic Venous Insufficiency & Varicose Veins", domain: "CardioLiverLongevity", route: "/heart/venous-insufficiency", consumerHook: "Heavy legs + varicose veins — horse chestnut + compression have real evidence.", packageConcept: "Vein Comfort Pack: horse chestnut HCSE Cochrane A-grade + gotu kola + Pycnogenol + medical-grade compression.", gradeMix: ["A", "B", "C", "T"], freshness: "fresh", risk: "moderate" },
];

export const DOMAIN_LABELS: Record<string, string> = {
  Skin: "Skin", Hair: "Hair", Metabolic: "Metabolic", Gut: "Gut",
  StressSleep: "Stress & Sleep", BrainEye: "Brain & Eye", MobilityEnergy: "Mobility & Energy",
  HormoneVitality: "Hormones & Vitality", ImmuneOral: "Immune & Oral", CardioLiverLongevity: "Cardio, Liver & Longevity",
};

export const getBundle = (id: string) => bundles.find((b) => b.id === id);
